# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Drag Labs
email: daslusan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is drag's domain. This blog will contain the innovations beyond your dreams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: daslusan
github_username:  lusan

# Build settings
markdown: kramdown
